services:
  db:
    image: postgres:latest
    container_name: quiz_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    ports:
      - "5437:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
